# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bench_solvetri <- function(n, X, y) {
    .Call(`_rlibkriging_bench_solvetri`, n, X, y)
}

bench_cholsym <- function(n, X) {
    .Call(`_rlibkriging_bench_cholsym`, n, X)
}

bench_invsympd <- function(n, X) {
    .Call(`_rlibkriging_bench_invsympd`, n, X)
}

bench_qr <- function(n, X) {
    .Call(`_rlibkriging_bench_qr`, n, X)
}

bench_LogLik <- function(n, ordinaryKriging, theta) {
    .Call(`_rlibkriging_bench_LogLik`, n, ordinaryKriging, theta)
}

bench_LogLikGrad <- function(n, ordinaryKriging, theta) {
    .Call(`_rlibkriging_bench_LogLikGrad`, n, ordinaryKriging, theta)
}

new_Kriging <- function(kernel) {
    .Call(`_rlibkriging_new_Kriging`, kernel)
}

new_KrigingFit <- function(y, X, kernel, regmodel = "constant", normalize = FALSE, optim = "BFGS", objective = "LL", parameters = NULL) {
    .Call(`_rlibkriging_new_KrigingFit`, y, X, kernel, regmodel, normalize, optim, objective, parameters)
}

kriging_fit <- function(k, y, X, regmodel = "constant", normalize = FALSE, optim = "BFGS", objective = "LL", parameters = NULL) {
    invisible(.Call(`_rlibkriging_kriging_fit`, k, y, X, regmodel, normalize, optim, objective, parameters))
}

kriging_copy <- function(k) {
    .Call(`_rlibkriging_kriging_copy`, k)
}

kriging_model <- function(k) {
    .Call(`_rlibkriging_kriging_model`, k)
}

kriging_summary <- function(k) {
    .Call(`_rlibkriging_kriging_summary`, k)
}

kriging_predict <- function(k, X, stdev = TRUE, cov = FALSE, deriv = FALSE) {
    .Call(`_rlibkriging_kriging_predict`, k, X, stdev, cov, deriv)
}

kriging_simulate <- function(k, nsim, seed, X) {
    .Call(`_rlibkriging_kriging_simulate`, k, nsim, seed, X)
}

kriging_update <- function(k, y, X) {
    invisible(.Call(`_rlibkriging_kriging_update`, k, y, X))
}

kriging_logLikelihoodFun <- function(k, theta, grad = FALSE, hess = FALSE) {
    .Call(`_rlibkriging_kriging_logLikelihoodFun`, k, theta, grad, hess)
}

kriging_logLikelihood <- function(k) {
    .Call(`_rlibkriging_kriging_logLikelihood`, k)
}

kriging_leaveOneOutFun <- function(k, theta, grad = FALSE) {
    .Call(`_rlibkriging_kriging_leaveOneOutFun`, k, theta, grad)
}

kriging_leaveOneOut <- function(k) {
    .Call(`_rlibkriging_kriging_leaveOneOut`, k)
}

kriging_logMargPostFun <- function(k, theta, grad = FALSE) {
    .Call(`_rlibkriging_kriging_logMargPostFun`, k, theta, grad)
}

kriging_logMargPost <- function(k) {
    .Call(`_rlibkriging_kriging_logMargPost`, k)
}

kriging_kernel <- function(k) {
    .Call(`_rlibkriging_kriging_kernel`, k)
}

kriging_optim <- function(k) {
    .Call(`_rlibkriging_kriging_optim`, k)
}

kriging_objective <- function(k) {
    .Call(`_rlibkriging_kriging_objective`, k)
}

kriging_X <- function(k) {
    .Call(`_rlibkriging_kriging_X`, k)
}

kriging_centerX <- function(k) {
    .Call(`_rlibkriging_kriging_centerX`, k)
}

kriging_scaleX <- function(k) {
    .Call(`_rlibkriging_kriging_scaleX`, k)
}

kriging_y <- function(k) {
    .Call(`_rlibkriging_kriging_y`, k)
}

kriging_centerY <- function(k) {
    .Call(`_rlibkriging_kriging_centerY`, k)
}

kriging_scaleY <- function(k) {
    .Call(`_rlibkriging_kriging_scaleY`, k)
}

kriging_normalize <- function(k) {
    .Call(`_rlibkriging_kriging_normalize`, k)
}

kriging_regmodel <- function(k) {
    .Call(`_rlibkriging_kriging_regmodel`, k)
}

kriging_F <- function(k) {
    .Call(`_rlibkriging_kriging_F`, k)
}

kriging_T <- function(k) {
    .Call(`_rlibkriging_kriging_T`, k)
}

kriging_M <- function(k) {
    .Call(`_rlibkriging_kriging_M`, k)
}

kriging_z <- function(k) {
    .Call(`_rlibkriging_kriging_z`, k)
}

kriging_beta <- function(k) {
    .Call(`_rlibkriging_kriging_beta`, k)
}

kriging_is_beta_estim <- function(k) {
    .Call(`_rlibkriging_kriging_is_beta_estim`, k)
}

kriging_theta <- function(k) {
    .Call(`_rlibkriging_kriging_theta`, k)
}

kriging_is_theta_estim <- function(k) {
    .Call(`_rlibkriging_kriging_is_theta_estim`, k)
}

kriging_sigma2 <- function(k) {
    .Call(`_rlibkriging_kriging_sigma2`, k)
}

kriging_is_sigma2_estim <- function(k) {
    .Call(`_rlibkriging_kriging_is_sigma2_estim`, k)
}

linalg_get_num_nugget <- function() {
    .Call(`_rlibkriging_linalg_get_num_nugget`)
}

linalg_set_num_nugget <- function(nugget) {
    invisible(.Call(`_rlibkriging_linalg_set_num_nugget`, nugget))
}

linalg_chol_safe <- function(X) {
    .Call(`_rlibkriging_linalg_chol_safe`, X)
}

new_NoiseKriging <- function(kernel) {
    .Call(`_rlibkriging_new_NoiseKriging`, kernel)
}

new_NoiseKrigingFit <- function(y, noise, X, kernel, regmodel = "constant", normalize = FALSE, optim = "BFGS", objective = "LL", parameters = NULL) {
    .Call(`_rlibkriging_new_NoiseKrigingFit`, y, noise, X, kernel, regmodel, normalize, optim, objective, parameters)
}

noisekriging_fit <- function(k, y, noise, X, regmodel = "constant", normalize = FALSE, optim = "BFGS", objective = "LL", parameters = NULL) {
    invisible(.Call(`_rlibkriging_noisekriging_fit`, k, y, noise, X, regmodel, normalize, optim, objective, parameters))
}

noisekriging_copy <- function(k) {
    .Call(`_rlibkriging_noisekriging_copy`, k)
}

noisekriging_model <- function(k) {
    .Call(`_rlibkriging_noisekriging_model`, k)
}

noisekriging_summary <- function(k) {
    .Call(`_rlibkriging_noisekriging_summary`, k)
}

noisekriging_predict <- function(k, X, stdev = TRUE, cov = FALSE, deriv = FALSE) {
    .Call(`_rlibkriging_noisekriging_predict`, k, X, stdev, cov, deriv)
}

noisekriging_simulate <- function(k, nsim, seed, X) {
    .Call(`_rlibkriging_noisekriging_simulate`, k, nsim, seed, X)
}

noisekriging_update <- function(k, y, noise, X) {
    invisible(.Call(`_rlibkriging_noisekriging_update`, k, y, noise, X))
}

noisekriging_logLikelihoodFun <- function(k, theta_sigma2, grad = FALSE) {
    .Call(`_rlibkriging_noisekriging_logLikelihoodFun`, k, theta_sigma2, grad)
}

noisekriging_logLikelihood <- function(k) {
    .Call(`_rlibkriging_noisekriging_logLikelihood`, k)
}

noisekriging_kernel <- function(k) {
    .Call(`_rlibkriging_noisekriging_kernel`, k)
}

noisekriging_optim <- function(k) {
    .Call(`_rlibkriging_noisekriging_optim`, k)
}

noisekriging_objective <- function(k) {
    .Call(`_rlibkriging_noisekriging_objective`, k)
}

noisekriging_X <- function(k) {
    .Call(`_rlibkriging_noisekriging_X`, k)
}

noisekriging_centerX <- function(k) {
    .Call(`_rlibkriging_noisekriging_centerX`, k)
}

noisekriging_scaleX <- function(k) {
    .Call(`_rlibkriging_noisekriging_scaleX`, k)
}

noisekriging_y <- function(k) {
    .Call(`_rlibkriging_noisekriging_y`, k)
}

noisekriging_noise <- function(k) {
    .Call(`_rlibkriging_noisekriging_noise`, k)
}

noisekriging_centerY <- function(k) {
    .Call(`_rlibkriging_noisekriging_centerY`, k)
}

noisekriging_scaleY <- function(k) {
    .Call(`_rlibkriging_noisekriging_scaleY`, k)
}

noisekriging_normalize <- function(k) {
    .Call(`_rlibkriging_noisekriging_normalize`, k)
}

noisekriging_regmodel <- function(k) {
    .Call(`_rlibkriging_noisekriging_regmodel`, k)
}

noisekriging_F <- function(k) {
    .Call(`_rlibkriging_noisekriging_F`, k)
}

noisekriging_T <- function(k) {
    .Call(`_rlibkriging_noisekriging_T`, k)
}

noisekriging_M <- function(k) {
    .Call(`_rlibkriging_noisekriging_M`, k)
}

noisekriging_z <- function(k) {
    .Call(`_rlibkriging_noisekriging_z`, k)
}

noisekriging_beta <- function(k) {
    .Call(`_rlibkriging_noisekriging_beta`, k)
}

noisekriging_is_beta_estim <- function(k) {
    .Call(`_rlibkriging_noisekriging_is_beta_estim`, k)
}

noisekriging_theta <- function(k) {
    .Call(`_rlibkriging_noisekriging_theta`, k)
}

noisekriging_is_theta_estim <- function(k) {
    .Call(`_rlibkriging_noisekriging_is_theta_estim`, k)
}

noisekriging_sigma2 <- function(k) {
    .Call(`_rlibkriging_noisekriging_sigma2`, k)
}

noisekriging_is_sigma2_estim <- function(k) {
    .Call(`_rlibkriging_noisekriging_is_sigma2_estim`, k)
}

new_NuggetKriging <- function(kernel) {
    .Call(`_rlibkriging_new_NuggetKriging`, kernel)
}

new_NuggetKrigingFit <- function(y, X, kernel, regmodel = "constant", normalize = FALSE, optim = "BFGS", objective = "LL", parameters = NULL) {
    .Call(`_rlibkriging_new_NuggetKrigingFit`, y, X, kernel, regmodel, normalize, optim, objective, parameters)
}

nuggetkriging_fit <- function(k, y, X, regmodel = "constant", normalize = FALSE, optim = "BFGS", objective = "LL", parameters = NULL) {
    invisible(.Call(`_rlibkriging_nuggetkriging_fit`, k, y, X, regmodel, normalize, optim, objective, parameters))
}

nuggetkriging_copy <- function(k) {
    .Call(`_rlibkriging_nuggetkriging_copy`, k)
}

nuggetkriging_model <- function(k) {
    .Call(`_rlibkriging_nuggetkriging_model`, k)
}

nuggetkriging_summary <- function(k) {
    .Call(`_rlibkriging_nuggetkriging_summary`, k)
}

nuggetkriging_predict <- function(k, X, stdev = TRUE, cov = FALSE, deriv = FALSE) {
    .Call(`_rlibkriging_nuggetkriging_predict`, k, X, stdev, cov, deriv)
}

nuggetkriging_simulate <- function(k, nsim, seed, X) {
    .Call(`_rlibkriging_nuggetkriging_simulate`, k, nsim, seed, X)
}

nuggetkriging_update <- function(k, y, X) {
    invisible(.Call(`_rlibkriging_nuggetkriging_update`, k, y, X))
}

nuggetkriging_logLikelihoodFun <- function(k, theta_alpha, grad = FALSE) {
    .Call(`_rlibkriging_nuggetkriging_logLikelihoodFun`, k, theta_alpha, grad)
}

nuggetkriging_logLikelihood <- function(k) {
    .Call(`_rlibkriging_nuggetkriging_logLikelihood`, k)
}

nuggetkriging_logMargPostFun <- function(k, theta, grad = FALSE) {
    .Call(`_rlibkriging_nuggetkriging_logMargPostFun`, k, theta, grad)
}

nuggetkriging_logMargPost <- function(k) {
    .Call(`_rlibkriging_nuggetkriging_logMargPost`, k)
}

nuggetkriging_kernel <- function(k) {
    .Call(`_rlibkriging_nuggetkriging_kernel`, k)
}

nuggetkriging_optim <- function(k) {
    .Call(`_rlibkriging_nuggetkriging_optim`, k)
}

nuggetkriging_objective <- function(k) {
    .Call(`_rlibkriging_nuggetkriging_objective`, k)
}

nuggetkriging_X <- function(k) {
    .Call(`_rlibkriging_nuggetkriging_X`, k)
}

nuggetkriging_centerX <- function(k) {
    .Call(`_rlibkriging_nuggetkriging_centerX`, k)
}

nuggetkriging_scaleX <- function(k) {
    .Call(`_rlibkriging_nuggetkriging_scaleX`, k)
}

nuggetkriging_y <- function(k) {
    .Call(`_rlibkriging_nuggetkriging_y`, k)
}

nuggetkriging_centerY <- function(k) {
    .Call(`_rlibkriging_nuggetkriging_centerY`, k)
}

nuggetkriging_scaleY <- function(k) {
    .Call(`_rlibkriging_nuggetkriging_scaleY`, k)
}

nuggetkriging_normalize <- function(k) {
    .Call(`_rlibkriging_nuggetkriging_normalize`, k)
}

nuggetkriging_regmodel <- function(k) {
    .Call(`_rlibkriging_nuggetkriging_regmodel`, k)
}

nuggetkriging_F <- function(k) {
    .Call(`_rlibkriging_nuggetkriging_F`, k)
}

nuggetkriging_T <- function(k) {
    .Call(`_rlibkriging_nuggetkriging_T`, k)
}

nuggetkriging_M <- function(k) {
    .Call(`_rlibkriging_nuggetkriging_M`, k)
}

nuggetkriging_z <- function(k) {
    .Call(`_rlibkriging_nuggetkriging_z`, k)
}

nuggetkriging_beta <- function(k) {
    .Call(`_rlibkriging_nuggetkriging_beta`, k)
}

nuggetkriging_is_beta_estim <- function(k) {
    .Call(`_rlibkriging_nuggetkriging_is_beta_estim`, k)
}

nuggetkriging_theta <- function(k) {
    .Call(`_rlibkriging_nuggetkriging_theta`, k)
}

nuggetkriging_is_theta_estim <- function(k) {
    .Call(`_rlibkriging_nuggetkriging_is_theta_estim`, k)
}

nuggetkriging_sigma2 <- function(k) {
    .Call(`_rlibkriging_nuggetkriging_sigma2`, k)
}

nuggetkriging_is_sigma2_estim <- function(k) {
    .Call(`_rlibkriging_nuggetkriging_is_sigma2_estim`, k)
}

nuggetkriging_nugget <- function(k) {
    .Call(`_rlibkriging_nuggetkriging_nugget`, k)
}

nuggetkriging_is_nugget_estim <- function(k) {
    .Call(`_rlibkriging_nuggetkriging_is_nugget_estim`, k)
}

optim_is_reparametrized <- function() {
    .Call(`_rlibkriging_optim_is_reparametrized`)
}

optim_use_reparametrize <- function(reparametrize) {
    invisible(.Call(`_rlibkriging_optim_use_reparametrize`, reparametrize))
}

optim_get_theta_lower_factor <- function() {
    .Call(`_rlibkriging_optim_get_theta_lower_factor`)
}

optim_set_theta_lower_factor <- function(theta_lower_factor) {
    invisible(.Call(`_rlibkriging_optim_set_theta_lower_factor`, theta_lower_factor))
}

optim_get_theta_upper_factor <- function() {
    .Call(`_rlibkriging_optim_get_theta_upper_factor`)
}

optim_set_theta_upper_factor <- function(theta_upper_factor) {
    invisible(.Call(`_rlibkriging_optim_set_theta_upper_factor`, theta_upper_factor))
}

optim_variogram_bounds_heuristic_used <- function() {
    .Call(`_rlibkriging_optim_variogram_bounds_heuristic_used`)
}

optim_use_variogram_bounds_heuristic <- function(variogram_bounds_heuristic) {
    invisible(.Call(`_rlibkriging_optim_use_variogram_bounds_heuristic`, variogram_bounds_heuristic))
}

optim_log <- function(l) {
    invisible(.Call(`_rlibkriging_optim_log`, l))
}

optim_get_max_iteration <- function() {
    .Call(`_rlibkriging_optim_get_max_iteration`)
}

optim_set_max_iteration <- function(max_iteration) {
    invisible(.Call(`_rlibkriging_optim_set_max_iteration`, max_iteration))
}

optim_get_gradient_tolerance <- function() {
    .Call(`_rlibkriging_optim_get_gradient_tolerance`)
}

optim_set_gradient_tolerance <- function(gradient_tolerance) {
    invisible(.Call(`_rlibkriging_optim_set_gradient_tolerance`, gradient_tolerance))
}

optim_get_objective_rel_tolerance <- function() {
    .Call(`_rlibkriging_optim_get_objective_rel_tolerance`)
}

optim_set_objective_rel_tolerance <- function(objective_rel_tolerance) {
    invisible(.Call(`_rlibkriging_optim_set_objective_rel_tolerance`, objective_rel_tolerance))
}

random_reset_seed <- function(seed) {
    invisible(.Call(`_rlibkriging_random_reset_seed`, seed))
}

random_randu <- function() {
    .Call(`_rlibkriging_random_randu`)
}

random_randu_vec <- function(n) {
    .Call(`_rlibkriging_random_randu_vec`, n)
}

random_randu_mat <- function(n, d) {
    .Call(`_rlibkriging_random_randu_mat`, n, d)
}

